server:
  port: 8181

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_blog
    username: root
    password: my-secret-pw